app: video-remove-silence
component: autoeditor-video-or-audio
core: autoeditor
version: 1.0.10

# cronjob:
#   schedule: "* * * * *"
deployment:
  replicas: 1
  sendlogs: "true"
  ports:
  - name: "5000-vrs"
    containerPort: 5000
    protocol: TCP
  env:
    - name: "TZ"
      value: "America/Sao_Paulo"
    #auto-editor
    - name: AUTO_EDITOR_MARGIN
      value: "0.06sec,0.4sec"
    #minio
    - name: MINIO_URL
      value: "svc-minio-api.minio.svc.cluster.local"
    - name: MINIO_PORT
      value: "9000"
    - name: MINIO_ROOT_USER
      valueFrom:
        secretKeyRef:
          name: s-minio
          key: MINIO_ACCESS_KEY
    - name: MINIO_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: s-minio
          key: MINIO_SECRET_KEY
    # rabbitmq
    - name: RABBITMQ_HOST
      value: "svc-rabbitmq.rabbitmq.svc.cluster.local"
    - name: RABBITMQ_PORT
      value: "5672"
    - name: RABBITMQ_VHOST
      value: "syrin"
    - name: RABBITMQ_USER
      valueFrom:
        secretKeyRef:
          name: s-rabbitmq
          key: RABBITMQ_DEFAULT_USER
    - name: RABBITMQ_PASS
      valueFrom:
        secretKeyRef:
          name: s-rabbitmq
          key: RABBITMQ_DEFAULT_PASS
  command:
    - exec: "python"
    - exec: "main.py"
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "6Gi"
      cpu: "8.0"
  affinity:
    hosts:
      - name: k8s-03
      - name: k8s-04

  # restartPolicy: OnFailure
  # ttlSecondsAfterFinished: 7200
  # concurrencyPolicy: Forbid
  # successfulJobsHistoryLimit: 1
  # failedJobsHistoryLimit: 2

services:
  - name: svc-video-remove-silence
    type: ClusterIP
    selector:
      app: video-remove-silence
      component: autoeditor-video-or-audio
    ports:
      - name: 5000-vrs-tcp
        port: 80
        targetPort: 5000
        protocol: TCP

