name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'requirements.txt'
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/video-remove-silence:latest
            ghcr.io/${{ github.repository_owner }}/video-remove-silence:1.0.${{ github.run_number }}

      - name: Log out of GitHub Container Registry
        run: docker logout ghcr.io

      - name: Update version in values.yaml
        run: |
          VERSION=1.0.${{ github.run_number }}
          FILE_PATH="helm/values.yaml"
          sed -i "s/^version: .*/version: ${VERSION}/" $FILE_PATH

      - name: Commit and push updated values.yaml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add helm/values.yaml
          git commit -m "Update version to ${VERSION}"
          git push origin main